### ISSUE TITLE
Vivaldi support

### ISSUE THREAD

**Issue by Crayder** [Xeo786/Rufaydium-Webdriver#1]
I'm currently trying to use the Chrome driver to launch a Vivaldi session. I've done this before in the past, but it seems Vivaldi changed it's versioning:

![image](https://github.com/Xeo786/Rufaydium-Webdriver/assets/9919010/908a64a1-4aa0-4b32-9689-844634cac30d)

This version of Vivaldi should be using the 120 version of the Chrome driver. But the Vivaldi version seems to be throwing off the version check. Is there a way around this?

**Comment by Xeo786** [comment]
With new session pass Viviladi Exe Path 

```
Browser := New Rufaydium()
instance := Browser.NewSession(ViviladiExePath)
```

**Comment by Crayder** [comment]
I've tried that already. Same error with or without unfortunately.
Latest version of everything, still happens:

![image](https://github.com/Xeo786/Rufaydium-Webdriver/assets/9919010/f0d51218-ca94-4a42-889f-d54c29403851)

---------

This is my entire script for testing, as an example:

```ahk
#SingleInstance, Force
#Persistent
#NoEnv
SendMode Input
SetWorkingDir, %A_ScriptDir%
SetWinDelay, 0
OnExit("EndSessions")

#Include ../Rufaydium/Rufaydium.ahk

browserPath := "C:\Users\ciles\Desktop\Vivald\Application\vivaldi.exe"
browserDriver := "chromedriver.exe"

Browser := new Rufaydium(browserDriver)
Browser.capabilities.Setbinary(browserPath)

; Set `--new-window` argument so that each new session will have it's own window. 
Browser.capabilities.addArg("--new-window")
Browser.capabilities.addArg("--profile-directory=Default")
Browser.capabilities.addArg("--app=https://www.youtube.com")

; "C:\Users\ciles\Desktop\Vivald\Application\vivaldi.exe" --new-window --profile-directory=Default --app=https://www.youtube.com
BrowserSession := browser.NewSession(browserPath)

return

EndSessions() {
    global Browser
    Browser.QuitAllSessions()
    Browser.Driver.Exit()
    ExitApp, 
    return
}
```

**Comment by Xeo786** [comment]
While creating Browser Session Rufaydium check for Browser version with viviladi version which does not matches, 
I haven't put support for Viviladi, but all the methods would work fine, you just need to modify Rufaydium class to skip version check for viviladi

**Comment by Crayder** [comment]
Fair answer to me, I'll take a look!
