### ISSUE TITLE
Typos on .getSession section.

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#10]
I wasn't able to get this to work until ahk7 provided examples on the forum. https://www.autohotkey.com/boards/viewtopic.php?p=463249&sid=bc28b0d3dbcd6fcc82da8f5923831f53#p463249

Rufaydium.getSession should be **Chrome**.getSession.

Session := ~~Rufaydium~~ **Chrome**.getSession(1) ; this will return with Session by number sequencing from first created to latest created
Session := ~~Rufaydium~~ **Chrome**.getSession(1,2) ; this will return with first session and switch Second tab, Tabs count from left to right
Session := ~~Rufaydium~~ **Chrome**.getSessionByUrl(URL)
Session2 := ~~Rufaydium~~ **Chrome**.getSessionByTitle(Title)

Thanks!

**Comment by Xeo786** [comment]
Thanks for pointing out .....just corrected
