### ISSUE TITLE
Chrome.capabilities.setUserProfile("Default") does not work with Edge.

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#15]
I'm not sure if this is due to my organization's policies, but I can't figure out what argument to use with Edge to get it to open. "Default", "Work", "Profile 1", etc. will all make Edge crash immediately, as does leaving it blank. 

Commenting out the line allows it to open, upon which I am automatically logged into my work account. I'd prefer to explicitly choose the profile. 

I tried changing the `userDataDir`, but this didn't work.

`userDataDir := "C:/Users/" A_UserName "/AppData/Local/Microsoft/Edge/User Data"`

Any ideas?

**Comment by Xeo786** [comment]
Edge User Profile location issue has been solved please check and remove the issue.
