### ISSUE TITLE
Session.CDP not working with Edge.

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#16]
I'm attempting to modify the DOM, and a script that works perfectly fine in Chrome does not work with Edge.

`Session.CDP.Navigate("https://www.example.com")` works in Chrome but not in Edge. Removing ".CDP" will work in both.

`Session.CDP.Evaluate("document.getElementById('logo_status').outerHTML = ''")` works in Chrome but not in Edge.

Is there maybe something in CDP.ahk that is different between the two?

**Comment by Xeo786** [comment]
Edge Driver might not support CDP you can use execute sync method to evaluate JS
