### ISSUE TITLE
Inquiring About Frame Optimization

### ISSUE THREAD

**Issue by mrdav87** [Xeo786/Rufaydium-Webdriver#2]
Hello everyone! 

I’m writing to inquire about any optimizations for Frames. Specifically, I’m dealing with more complex scenarios than the Tab1 example, where there are triggered frames. My question is: Is it possible to integrate a function that calls a frame by its ID attribute? I hope you are already working on a solution. 

I’d also like to express my gratitude for the outstanding work you’ve done. Currently, your library is the best out there! I eagerly await your response. Thank you very much!

**Comment by Xeo786** [comment]
thank you,
I am working on Rufaydium v2 for AHK V2 in slow pace,  in there there a Method called `GetFrame()` which return with map() of frames structure

You can download it there
https://www.the-automator.com/downloads/rufaydium-in-v2/
