### ISSUE TITLE
interact with tabs without activating them

### ISSUE THREAD

**Issue by otomay** [Xeo786/Rufaydium-Webdriver#26]
Hello!

Is it possible to interact with several tabs of a single session (sending and collecting values, clicking, etc) without activating the said tabs?

I tried:

```
Tab1 := Chrome.getSession(1,1)
Tab2 := Chrome.getSession(1,2)
```
But when using

```
Msgbox % Tab1
Msgbox % Tab2
```

The returned url is always of the active tab

Thank's for your time

**Comment by Xeo786** [comment]
You can create new tabs within the same session by using [Session.NewTab()](https://github.com/Xeo786/Rufaydium-Webdriver#sessionnewtab--sessionnewwindow), but you cannot get a separate pointer for a specific tab within one session as one session can only have one active tab/switched.

You can write an AHK class to get the tab's/window pointer, but that class has to [switch](https://github.com/Xeo786/Rufaydium-Webdriver#switchtab-switchbytitle--switchbyurl-activetab) the tab/window every time whenever that pointer is used. but I have already written a simple function to get specific tab, 

```
; if there are two tabs in one session
tab1 := GetRufaydium(URL1) 
tab2 := GetRufaydium(URL2)

; GetRufaydium(URL) gets existing session  
; stops us creating multiple sessions again and again 
; make sure not to manually close driver/chrome.driver.exit()
; by Xeo786
GetRufaydium(URL)
{
	; get chrome driver / runs chrome driver if not running, download driver if available in A_ScriptDir
	; Run Chrome Driver with default parameters and loads deafult capabilities
	Chrome := new Rufaydium() 
	Page := Chrome.getSessionByUrl(URL) ; check page (created by driver) if already exist 
	if !isobject(page) ; checcking if Session with url exist
	{
		Page := Chrome.getSession(1,1) ; try getting first session first tab
		if isobject(page) ; if exist 
			Page.NewTab() ; create new tab instead new session
		else ; if does not exist 
			Page := Chrome.NewSession() ; create new session ; Page.Exit() if any session manually closed by user which causes lag
		Page.Navigate(URL) ; navigate		
	}
	return page 
}
```

**Comment by otomay** [comment]
Oh, I see! Thanks for the help, the tab function idea will help me in othe project. But for what I thought, I'll have to use another session. I think it will be more stable, since I intend to get data without displaying the page on the screen.
