### ISSUE TITLE
Portable + Incognito?

### ISSUE THREAD

**Issue by erohtar** [Xeo786/Rufaydium-Webdriver#27]
Hi, I currently use SeleniumBasic to automate Chrome under AHK (I've tried chrome.ahk as well, with mixed results).

I use SeleniumBasic with Chrome **Portable** and **Custom Profile folder** in incognito mode, and that gives me the cleanest and most portable environment that works quite reliably on multiple computers, including the ones where Chrome is not installed or is not the default browser.

I wanted to ask you how would I use Rufaydium the same way? 
- Custom Chrome.exe path
- Custom Profile folder path
- Optionally enable Incognito while launching Chrome

Thank you!

**Comment by Xeo786** [comment]
- [Binary](https://github.com/Xeo786/Rufaydium-Webdriver#binary) is the Executable file location, Binary can be your portable chrome.exe file location
- You can also pass UserDataDir see [example](https://github.com/Xeo786/Rufaydium-Webdriver#capabilities-class)
- Incognito mode [example](https://github.com/Xeo786/Rufaydium-Webdriver#enable-incognito-mode)

**Comment by Xeo786** [comment]
Where you have placed the chromedriver.exe, if its `A_ScriptDir` then this should work `Chrome := new Rufaydium("chromedriver.exe")`
if its somewhere else you need to pass the location `Chrome := new Rufaydium("E:\Somefolder\chromedriver.exe")`

Protable chrome version should match ChromeDriver version.

Following line, needs a folder to exist at location:  `C:\AHK\chromeProfileCb\Default` if there is not please create
```Chrome.capabilities.setUserProfile("Default","C:\AHK\chromeProfileCb\") ```

**Comment by erohtar** [comment]
> Where you have placed the chromedriver.exe, if its A_ScriptDir then this should work Chrome := new Rufaydium("chromedriver.exe")
if its somewhere else you need to pass the location Chrome := new Rufaydium("E:\Somefolder\chromedriver.exe")

Yes, I've put both chromedriver.exe and test.ahk in the Rufaydium folder

> Protable chrome version should match ChromeDriver version.

Yes, I've got the exact version for the Chrome I'm using portable (98.0.4758.102)

> Following line, needs a folder to exist at location: C:\AHK\chromeProfileCb\Default if there is not please create
Chrome.capabilities.setUserProfile("Default","C:\AHK\chromeProfileCb\")

Yes, here's a screenshot
![image](https://user-images.githubusercontent.com/5120628/205428395-d0521c6d-44cc-498d-90a8-60397b43e857.png)

> This window shows the script getting already navigated to the page.

But, nothing shows up. Is it headless by default?

**Comment by Xeo786** [comment]
There is an issue you can only do one of those, either you set capabilities to run chrome with a profile or use incognito mode, both conditions are opposite of each other.

**Comment by erohtar** [comment]
> There is an issue you can only do one of those, either you set capabilities to run chrome with a profile or use incognito mode. both conditions are opposite of each other.

I already tried that too - commented out the line enabling incognito, but still nothing. Tried it again just now to be sure:
![image](https://user-images.githubusercontent.com/5120628/205428722-22e86691-154e-4733-a171-9cf5ea2ffa91.png)

**Comment by erohtar** [comment]
I just tried an older portable chrome I used to use (v78.0.3904.108) with its chromedriver I just downloaded - same results.

Idk what I'm missing.

**Comment by Xeo786** [comment]
if chrome does not works then there should be some error, 
Try something like this,
Kill chromedriver.exe and chrome.exe fusing task manager 
try this code
```
#Include Rufaydium.ahk

Chrome := new Rufaydium("chromedriver.exe")
Chrome.Driver.Visible := true
msgbox, now check driver is running`nPress ok to continue
Page := Chrome.NewSession("E:\Portables2\Chrome\App\Chrome-bin\chrome.exe")
msgbox, % "Following address is copied to your clipboard`nAddress:" clipboard := Page.Address
Return
F12::
	Chrome.QuitAllSessions() ; close all session 
	Chrome.Driver.Exit() ; then exits driver
ExitApp
```
Use another browser and try to navigate to that address  to check if there is an existing session 
do something like paste address and add `\url` or `\title`

**Comment by Xeo786** [comment]
> I just tried an older portable chrome I used to use (v78.0.3904.108) with its chromedriver I just downloaded - same results.
> 
> Idk what I'm missing.

I never played with portables this might be some bug, I want to try portables, and will answer you in a few days

**Comment by erohtar** [comment]
Just did your test.
- Made sure chrome.exe and chromedriver.exe were not running
- Ran the script and during the first msgbox, chromedriver.exe was running
![image](https://user-images.githubusercontent.com/5120628/205429337-3ba4ea5c-8478-46b3-8754-cd3f9e4fdef4.png)
- Tried the copied url (http://127.0.0.1:9515/session/) in another browser and got this:
```
{"value":{"error":"invalid session id","message":"invalid session id","stacktrace":"Backtrace:\n\tOrdinal0 [0x004269A3+2582947]\n\tOrdinal0 [0x003BA6D1+2139857]\n\tOrdinal0 [0x002B3960+1063264]\n\tOrdinal0 [0x002D4BF0+1199088]\n\tOrdinal0 [0x002F8440+1344576]\n\tOrdinal0 [0x002F6358+1336152]\n\tOrdinal0 [0x002F5EF8+1335032]\n\tOrdinal0 [0x00295357+938839]\n\tOrdinal0 [0x002958D3+940243]\n\tOrdinal0 [0x00295C1A+941082]\n\tGetHandleVerifier [0x005CBE02+1675858]\n\tGetHandleVerifier [0x0068036C+2414524]\n\tGetHandleVerifier [0x004BBB01+560977]\n\tGetHandleVerifier [0x004BA8D3+556323]\n\tOrdinal0 [0x003C020E+2163214]\n\tOrdinal0 [0x002950D5+938197]\n\tOrdinal0 [0x00294AA8+936616]\n\tGetHandleVerifier [0x006A807C+2577612]\n\tBaseThreadInitThunk [0x76136359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77B97B74+228]\n\tRtlGetAppContainerNamedObjectPath [0x77B97B44+180]\n"}}
```
- chrome.exe was not running throughout

>  I want to try portables, and will answer you in a few days

Thank you! [This](https://portableapps.com/apps/internet/google_chrome_portable) is where I downloaded it.

**Comment by Xeo786** [comment]
> Just did your test.
> 
> * Made sure chrome.exe and chromedriver.exe were not running
> * Ran the script and during the first msgbox, chromedriver.exe was running
>   ![image](https://user-images.githubusercontent.com/5120628/205429337-3ba4ea5c-8478-46b3-8754-cd3f9e4fdef4.png)
> * Tried the copied url (http://127.0.0.1:9515/session/) in another browser and got this:
 at this line
`msgbox, % "Following address is copied to your clipboard`nAddress:" clipboard := Page.Address`
you should have copies 
```http://127.0.0.1:9515/session/<unique session id >```
if there is no session id there might be some bug for handling portables

**Comment by erohtar** [comment]
I see. I'll wait for your fix, thank you

**Comment by Xeo786** [comment]
It worked for me.
[PortableChrome.zip](https://github.com/Xeo786/Rufaydium-Webdriver/files/10146085/PortableChrome.zip)
See Test MsgBox.png inside Zip.
I downloaded from
>Thank you! [This](https://portableapps.com/apps/internet/google_chrome_portable) is where I downloaded it.

Actually I have a chrome installed too.

**Comment by erohtar** [comment]
Sorry but it still didn't work for me. I even downloaded their latest Chrome (meaning so far I've tried v78, v98 & v108)
Chrome doesn't even launch:
![image](https://user-images.githubusercontent.com/5120628/205444256-00c12ce6-e8a7-4022-983d-aae06fc944b7.png)

> Actually I have a chrome installed too.

That may have something to do with why it works for you..

**Comment by Xeo786** [comment]
Please close this issue.

**Comment by erohtar** [comment]
Problem is still open for me. Feel free to close it if you must.

**Comment by Xeo786** [comment]
You can install chrome and then check, if that works then this is issue for chrome driver developers

**Comment by erohtar** [comment]
If it works with Chrome installed then that beats the whole point of this thread. I need it to work without having to install anything.
