### ISSUE TITLE
Firefox: capabilities.setUserProfile not working if profile does'nt exist

### ISSUE THREAD

**Issue by manu3l** [Xeo786/Rufaydium-Webdriver#28]
Hi

Using Firefox, if you want to create/use a new profile:
Firefox.capabilities.setUserProfile("Ruf")  ; (same with another dir)
you get an error:
"session not created
Failed to set preferences: Unable to write Firefox profile: Le path is not found (os error 3)"

To fix it you have to update the \AppData\Roaming\Mozilla\Firefox\profiles.ini

Work fine for example with edge without extra change.
Is it possible to extends FireFoxCapabilities  ?

**Comment by Xeo786** [comment]
Hi 
Thanks for pointing out the bug, I have just fixed this [bug](https://github.com/Xeo786/Rufaydium-Webdriver/commit/169e7cfc2a20072e35d6d4b9352d925b086fa8af)

**Comment by manu3l** [comment]
It works now with the default path indeed. Thanks.

But if we use another path it create a ini file that doesn't seems to work/is in use.

example:
path := A_ScriptDir "\FF-profile"
Firefox.capabilities.setUserProfile("Ruf",path) ;
it will create a FF-profile.ini file in the a_scriptdir with
[Ruf]
Path=Profiles/Ruf
Name=Ruf
IsRelative=1

We got the same error as before. 
Andi if I change Path=Profiles/Ruf to Path=FF-profile/Ruf again same error.

**Comment by Xeo786** [comment]
Bug [fixed](https://github.com/Xeo786/Rufaydium-Webdriver/commit/f44a7c2b952909ea8c5baf2d8e2921619e05c3ba)

**Comment by manu3l** [comment]
Everything is fine.
Thanks.
