### ISSUE TITLE
Firefox Error

### ISSUE THREAD

**Issue by lilosh1203** [Xeo786/Rufaydium-Webdriver#29]
It no longer connects with Firefox. 
With previous versions everything is correct, but with the current version it doesn't connect. 
Same error presented by user sadaosh1970.
https://www.autohotkey.com/boards/viewtopic.php?p=499090#p499090

As Rufaydium works correctly with previous versions, it is assumed that the error was caused by updates after 03/12/2022.

**Comment by Xeo786** [comment]
Please elaborate, you can access every Firefox with old Rufaydium?
or you cannot access latest Firefox?
Because the latest firefox explained in [reply](https://www.autohotkey.com/boards/viewtopic.php?p=499192#p499192) to that post.

**Comment by lilosh1203** [comment]
The latest version Rufaydium does not work with any version of Firefox. 
The old version works with all versions of Firefox, even version 108.
I have been regularly downloading the most current versions by clicking on "Code" as below.
[https://github.com/Xeo786/Rufaydium-Webdriver/archive/refs/heads/main.zip](url)

 Can I use these most current versions or should I just use the versions that are available in "Releases" (Nov 4, 2022)?
[(https://github.com/Xeo786/Rufaydium-Webdriver/releases/tag/RufaydiumV1.7.2)](url)

**Comment by Xeo786** [comment]
Latest Firefox with the latest Rufaydium works but `getSession(SessionIndex,tab)` was not working due to wrong indexing. just fixed. 

if you still facing issues please share your code. how you create new sessions and re-access them.

**Comment by lilosh1203** [comment]
The error persists even with the latest update.
The ActiveSession.ini file is not created.
The script I tested is:

`#Include Rufaydium.ahk
Browser := new Rufaydium("geckodriver.exe") 
Session := Browser.NewSession() 
Session.Maximize() 
Session.url := "www.google.com" 
ExitApp`

It works on the old version from 3, December, 2022, but it doesn't work with the current one.

**Comment by Xeo786** [comment]
Run geckodriver manually I will show you driver version, check Firefox driver version, 
if Driver is latest and update your browser
if Browser is latest delete geckodriver Rufaydium will download the driver you can manually download driver too

**Comment by lilosh1203** [comment]
Geckodriver version: geckodriver 0.32.0 (4563dd583110 2022-10-13 09:22 +0000)
I deleted Geckodriver. Rufaydium downloaded the same version.
Firefox 108.0.1 (64-bits)
The error remains the same.

Going back to the previous version of 03/12/2022, everything works correctly again.

**Comment by Xeo786** [comment]
I found out your issue upon comparing both versions, sorry I didn't realize this until now.
What you were facing was a timeout issue when you create `newsession()` your setup takes more than 3 seconds to create a session. and HTTP requests will wait for 3 seconds, Which I assumed was enough time for a response but I was wrong.

so why older version work for you because they didn't have defined timeouts

Therefore, I introduce the `SetTimeouts()` method so users can change timeout at any place/time. 
See [changing]( https://github.com/Xeo786/Rufaydium-Webdriver/commit/82fbf09325a8e08a0a33bff1d063b2fe4315b8d8)

**Comment by lilosh1203** [comment]
I tested it here and the error no longer occurs.
Thank you very much!

I noticed another error with Firefox.
Even when Rufaydium is controlling Firefox, the "ready" parameter always returns "false".

Code:
#Include Rufaydium.ahk
Browser := new Rufaydium("geckodriver.exe") 
Session := Browser.NewSession() 
Check_Status := Browser.Status()
MsgBox, % Check_Status

**Comment by Xeo786** [comment]
Geckodriver can create one driver session. unlike chromrdriver which can handle multiple driver sessions

```autohotkey
FF := new Rufaydium("geckodriver")
msgbox, % FF.status() ; Driver is ready to create session
s := FF.NewSession() ; Session created 
msgbox, % FF.status() ; Driver is no ready as it is already enganged with a session
```
You can use `newWindow()` for another window connected to same session. or you need to create session using driver with different driver location and port.

**Comment by lilosh1203** [comment]
Thank you very much!
Your work is amazing.
Unbelievable that someone who never studied at a specific school for computer programming could solve such a good job. Congratulations!
