### ISSUE TITLE
Session.GetCookies() and Session.GetCookieName(Name) Examples

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#3]
```
array := Session.GetCookies()
MsgBox, % array[1].Name " | " array[1].Domain " | " array[1].Value 
```

```
var := Session.GetCookieName("CFID")
MsgBox, % var.Name " | " var.Value " | " var.HttpOnly " | " var.Domain " | " var.Size " | " var.Priority " | " var.ExpirationDate
```

https://developer.chrome.com/docs/extensions/reference/cookies/#type-Cookie

**Comment by Xeo786** [comment]
> ```
> array := Session.GetCookies()
> MsgBox, % array[1].Name " | " array[1].Domain " | " array[1].Value 
> ```
> 
> ```
> var := Session.GetCookieName("CFID")
> MsgBox, % var.Name " | " var.Value " | " var.HttpOnly " | " var.Domain " | " var.Size " | " var.Priority " | " var.ExpirationDate
> ```
> 
> https://developer.chrome.com/docs/extensions/reference/cookies/#type-Cookie

Ok I will add that into documents
