### ISSUE TITLE
page.getElementsbyXpath gives strange error in v2 Alpha

### ISSUE THREAD

**Issue by jrg63** [Xeo786/Rufaydium-Webdriver#30]
I tried to execute the following on https://500px.com/login:

browser := Rufaydium()
page := browser.NewSession()
page.url := "https://500px.com/login"
Sleep(10 * 1000) ; terrible but its just a test
buttons := page.getelementsbyXpath("//button[contains(., 'Log in')]"

![image](https://user-images.githubusercontent.com/25476144/223974112-6df7c7e7-0f89-498a-84c7-cbd948875fd2.png)

Any suggestions on how to fix this. I just started using AutoHotKey v2 and have successfully written a couple of web scripts using your alpha code but I was only using querySelector and querySelectorAll.

Thanks in advance for any assistance

**Comment by jrg63** [comment]
I tried making the change you suggested and still the same problem:

***@***.***

R:\Documents\AutoHotkey\Lib\Rufaydium-Webdriver\Session.ahk (167) : [Session.Prototype.findelements] e[A_Index] := Element(this.address "/element/" elementid, i)
R:\Documents\AutoHotkey\Lib\Rufaydium-Webdriver\Session.ahk (185) : [Session.Prototype.getElementsbyXpath] Return this.findelements(by.xPath,xPath)
R:\Documents\Dev\Projects\500px\500pxClasses\Web.ahk (83) : [Web.Prototype.Login] button := this.webPage.getElementsbyXpath("//button[contains(., 'Log in')]")
R:\Documents\Dev\Projects\500px\500pxClasses\Web.ahk (22) : [Web.Prototype.__New] this.Login(username, pwd)

Any other suggestions to try please?

**Comment by enaaab460** [comment]
I think I fixed findelements method in Elements.ahk by replacing it as follows
findelements(u, v)
	```
{
		e := []
		for k, elements in this.Send("elements", "POST", map("using", u, "value", v), 1)
		{
			for i, elementid in elements
				e.InsertAt(k,Element(this.address "/element/" elementid, i))
		}
		if e.Length > 0
			return e
		return 0
	}
```

**Comment by jrg63** [comment]
Thank you very much, that solved the problem, but you also need to make the same change in Session.ahk. This little test program worked successfully as a result:

#include <Rufaydium-Webdriver\Rufaydium>


startUrl := "https://500px.com/notifications"
kChromeWinTitle := "ahk_exe chrome.exe"

/*
    Kill chrome if its running
*/

if (WinExist(kChromeWinTitle))
{
    WinKill(kChromeWinTitle)
}

; invoke chrome
global browser := Rufaydium()
browser.capabilities.setUserProfile("Default")
; browser.capabilities.UserPrompt := "accept and notify"

; start a new session
global page := browser.NewSession()
page.URL := startUrl
Sleep(5 * 1000) ; terrible but its just a test
buttons := page.getelementsbyXpath("//span[contains(., 'Sign up')]")
buttons[1].click()

page.Quit()
browser.driver.Exit()

**Comment by jrg63** [comment]
I take it back. It has now broken the following lines that used to work:

                local elem := element.querySelector('#notifications-page-Content-0 > div > div > div')
                this.rawList := elem.querySelectorAll(':scope > div > div')

The first line gets the container that holds a variable # of divs. The second gets each div.

I also tested undoing the changes to Session.ahk and it still breaks them.

**Comment by enaaab460** [comment]
> I think I fixed findelements method in Elements.ahk by replacing it as follows
> 
> ```
> findelements(u, v)
> {
> 	e := []
> 	for k, elements in this.Send("elements", "POST", map("using", u, "value", v), 1)
> 	{
> 		for i, elementid in elements
> 			e.InsertAt(k-1,Element(this.address "/element/" elementid, i))
> 	}
> 	if e.Length > 0
> 		return e
> 	return 0
> }
> ```
> 
> I think part of the problem was that the outer loop was using Element as map value, and the innermost loop was using walling Element class, so I changed the map to Elements. Then I used insertat to push to the e array

My bad,  I meant to say sessions.ahk
I didn't edit elements.ahk

**Comment by enaaab460** [comment]
> I take it back. It has now broken the following lines that used to work:
> 
> ```
>             local elem := element.querySelector('#notifications-page-Content-0 > div > div > div')
>             this.rawList := elem.querySelectorAll(':scope > div > div')
> ```
> 
> The first line gets the container that holds a variable # of divs. The second gets each div.
> 
> I also tested undoing the changes to Session.ahk and it still breaks them.

I think the second line depends on findelements of element.ahk,  which I did not change or test

**Comment by enaaab460** [comment]
Element.querySelectorAll works fine with me

**Comment by enaaab460** [comment]
Just tried now. The original elements.ahk had the same error when using element.querySelectorAll().
When I made the same modifications as sessions.ahk it worked.
```
findelements(u,v)
	{
		e := []
		for k, elements in this.Send("elements","POST",map("using",u,"value",v),1)
		{
			for i, elementid in elements
			{
				address := RegExReplace(this.address "/element/" elementid,"(\/shadow\/.*)\/element","/element")
				address := RegExReplace(address "/element/" elementid,"(\/element\/.*)\/element","/element")
				; e[k-1] := Element(address,i)
				e.InsertAt(k-1,Element(address,i))
			}
		}

		; if e.count() > 0
		if e.Length > 0
			return e
		return 0
	}
```

**Comment by enaaab460** [comment]
```
browser:=Rufaydium()
document := browser.NewSession()
document.url := "facebook.com"
output:=""
for elem in document.querySelector('.x78zum5.xdt5ytf.x1iyjqo2.x1us19tq').querySelectorAll('a'){
    output.=elem.innerText "`n"
}
msgbox output
```
This test script gets the names of the links on the left sidebar on facebook's home feed page, and works after the modificiations I made to the elements.ahk
![image](https://user-images.githubusercontent.com/34572749/226279451-8259afb5-de4e-4b8f-91d0-01c3ed838ca0.png)

**Comment by Xeo786** [comment]
just noticed object element and element class object conflict. fixed it but array length return zero '0' when array start from '0' but as 1 item i.e. `array.InsertAt(0,"somvar") ` but count will return 1

**Comment by jrg63** [comment]
Thank you for looking into this further. I took a fork of the latest branch and am still having issues when I separate the query into 2 lines:

If I go onto the feedly.com landing page and execute the following in the console:

![image](https://user-images.githubusercontent.com/25476144/226481644-0926b070-1a53-4c9d-8895-79f571e5ab7d.png)

It returns an array of 4 elements which are the rows in the footer

If I write a small program to do the same thing in AHK:

; invoke chrome
global browser := Rufaydium()
browser.capabilities.setUserProfile("Default")
; browser.capabilities.UserPrompt := "accept and notify"

; start a new session
global page := browser.NewSession()
page.URL := "https://feedly.com"
Sleep(2 * 1000) ; terrible but its just a test

; get div at bottom of the page
f := page.querySelector(".LandingFooter")
i := f.querySelectorAll(":scope > div > div")

page.Quit()
browser.driver.Exit()

![image](https://user-images.githubusercontent.com/25476144/226481828-64a5762d-dab0-4282-93fa-3d274de6f105.png)

Since its an array that's being returned shouldn't Elements.ahk say the following:

if e.Length > 0 rather than e.Count since its not a map?

I also tested it with the following xpath line and my change worked correctly

x := page.getElementsbyXpath("//footer/div/div")

**Comment by enaaab460** [comment]
Today the developer and I figured out the fix, download the latest library
after they merge the latest pull request, or you can copy the changes from
requests 31 and 32 till they merge

**Comment by jrg63** [comment]
Awesome, I’ll wait for the merge

**Comment by Xeo786** [comment]
just merged
