### ISSUE TITLE
Closing a tab throws an exception Rufaydium V2 Alpha (Branch AHKV2)

### ISSUE THREAD

**Issue by jrg63** [Xeo786/Rufaydium-Webdriver#34]
I have a small test program that tries to create a tab and then close it

global page := browser.NewSession()
page.url := startUrl
aTab := page.NewTab()
page.SwitchTab(aTab)
page. Close()

The page. Close throws an exception as the code in Session.ahk is the following:

Tabs := this. Send("window","DELETE")
this.Switch(this.currentTab := tabs[tabs. Length()])

I believe the code should be changed to:

Tabs := this. Send("window","DELETE")
this.SwitchTab(this.currentTab := tabs[tabs. Length])

**Comment by Xeo786** [comment]
method `Newtab()` returns emprty.

This will create new tab without switching
```autohotkey
Session.NewTab(Activate:= false)
```
This will create new tab and switch to taht tab so you do not need to switch it manually
```authotkey
Session.NewTab(Activate:=True)
Session.NewTab() ; here Activate is by default true
```

**Comment by jrg63** [comment]
I am using the v2 alpha if that makes a difference:

Here’s a little program that I am using for testing:

    ; invoke chrome
    global browser := Rufaydium()
    browser.capabilities.setUserProfile("Default")
    ; browser.capabilities.UserPrompt := "accept and notify"

    ; start a new session
    global page := browser.NewSession()
    page.URL := https://feedly.com
    ; create a new tab
    nTab := page.NewTab()
    MsgBox "nTab = " nTab
    ; close the tab
    page.Close()
    ; close the session
    page.Close()

Here’s the output from the MsgBox statement:

***@***.***

Note that nTab has a return value which appears to be a tab id

When it hits the first page.close(), it produces the following exception:

***@***.***

Modifying the test program to do what you suggested

    ; create a new tab
    nTab := page.NewTab(Activate:=true)
    MsgBox "nTab = " nTab

It produces the following exception:

***@***.***

100% reproducible in each case

I double checked to make sure that I’m using the latest version of the source and I am.

**Comment by Xeo786** [comment]
Sorry, but you didn't mentioned this error is from V2Alpha. It is in alpha and I am not working on V2 right now I need to learn more about v2 

you should do something like to create and switch to active tab

```autohotkey
Session.SwitchTab( Session.newTab()) ; then Session.currentTab will have the current tab id
```

**Comment by Xeo786** [comment]
I just fixed Session.Close() just tried your code and found the bug and fixed it thanks.

**Comment by jrg63** [comment]
Awesome, thanks!
