### ISSUE TITLE
Using Edge Browser Sync your profile and web experience messages

### ISSUE THREAD

**Issue by GsynthChris** [Xeo786/Rufaydium-Webdriver#39]
Hello, 
Each time I launch an Edge browser session using Rufaydium I get the following 2 messages. 
![image](https://github.com/Xeo786/Rufaydium-Webdriver/assets/43126821/73976eed-8bf1-49e3-8b3d-30096b5a5483)

I don't get these messages when launching without Rufaydium.

**Comment by RaptorX** [comment]
maybe try using the default profile:

```
Edge := new Rufaydium("edge")
Edge.capabilities.setUserProfile("Profile 1")
Session := Edge.NewSession()
```

**Comment by GsynthChris** [comment]
Just got around to trying that out. Not able to launch with the setUserProfile option. Even tried using a different user name.
It does launch Edge but then this error pops up. 
![image](https://github.com/Xeo786/Rufaydium-Webdriver/assets/43126821/5e958e6d-77ae-4603-ac0b-77d0576d6cc1)

I see there is another open issue for this issue so maybe the reason I can't get this working is the same as that. 

As you can see from my commented out code... I have tried a number of things... haven't cracked it yet. 
![image](https://github.com/Xeo786/Rufaydium-Webdriver/assets/43126821/d1f6d696-1009-4810-b41f-c520b6d01edf)

**Comment by GsynthChris** [comment]
OMG! I figured it out... well rather.. the devs ALREADY figured it out. I downloaded the most recent code and that fixed it. 

I feel like a duffus. :D 

Closing out the issue. THANKS DEVS!
