### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by hi5** [Xeo786/Rufaydium-Webdriver#4]
You may want to consider adding a license to your code, tricky subject but Github has more info on it here https://github.blog/2013-07-15-choosing-an-open-source-license/ and https://choosealicense.com/

That way you at least will be credited (depending on your choice of course) or insist on spin-off projects to release their source.

Edit: more info and other licenses https://opensource.org/licenses

**Comment by Xeo786** [comment]
Even though I have worked with lawyer as drafter, when I was young but for licensing codes and lib, I am noob, all I did was draft suits and plaints about civil cases, please suggest what license I choose as I want to share this code as open source just like Autohotkey, I am confused what license should I select, as Rufaydium is 100% AHK  using Webdriver + W3C standard Rest calls + Chrome devtools protocols apis

**Comment by hi5** [comment]
First of all I'm no lawyer and don't know much about it either so don't take my word for it as such. But having _any_ licence is better than **none**, as no license might prevent people using it at work or as part of their program(s) as far as I understand it.

There are many licenses but you can probably trim it down to two or three choices if you want to allow it being used as free and widely as possible.

Note that on Wikipedia you'll find the descriptions of most licenses with some history of what is/isn't good about it (according to those editing these entries of course, but it gives you some insights into the discussions which is interesting to read)

There is no rush to add a licence so you can do some research, there is a nice table here https://choosealicense.com/appendix/ or here https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

1.
    * If you really don't care what happens (e.g. someone removing your name from the code for example, commercial use etc) Ahk2Exe uses the crudely titled WTFPL ( note that it doesn't seem to be listed/approved https://opensource.org/licenses/alphabetical as such )
WTFPL license https://github.com/AutoHotkey/Ahk2Exe/blob/master/COPYING
    * A nicer one with similar purpose seems to be The Unlicense as used often by just me
https://github.com/AHK-just-me/Class_SQLiteDB/blob/master/LICENSE

2) AutoHotkey uses GPL which _might_ be an issue for use in companies or as part of other programs (companies seem to shy away from it it as they might have to share their sources which they don't want (at least that is how I understand it))
https://github.com/Lexikos/AutoHotkey_L
GPL 2 https://github.com/Lexikos/AutoHotkey_L/blob/master/license.txt

3) MIT seems to be a popular choice in general:
https://choosealicense.com/licenses/mit/
(people will have to keep your name in the code/license)

**Comment by hi5** [comment]
> Webdriver + W3C standard Rest calls + Chrome devtools protocols apis

That goes for many libraries/frameworks that do the same, just a quick search on Github for inspiration:
https://github.com/florentbr/SeleniumBasic
https://github.com/seleniumbase/SeleniumBase
https://github.com/tebeka/selenium
https://github.com/robotframework/SeleniumLibrary
etc

**Comment by Xeo786** [comment]
I read through all of this and MIT seems better, 
Thank you so much.
