### ISSUE TITLE
Session.Screenshot("picture location") creates a "File" file without .png extension

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#4]
Took me a bit to figure out how this works and where it saves by default since the parameter says "location:=0" but in essence is really the filename.

Perhaps it is implied we should add the extension, but since the example doesn't include it, and says only PNG works, maybe it would add it automatically or something?

![image](https://user-images.githubusercontent.com/32589808/168530641-46ad61c8-71f4-4e96-8cdb-32439e78df19.png)

Entering the whole filename with extension correctly creates the file. Apparently .jpg works too!

![image](https://user-images.githubusercontent.com/32589808/168530913-400da3c3-24a6-4295-b823-5f121aa51b08.png)

Maybe having a second optional parameter for "format" that defaults to .png could be useful?

**Comment by Xeo786** [comment]
Fixed examples in Readme.md
