### ISSUE TITLE
Opera (more fyi)

### ISSUE THREAD

**Issue by hi5** [Xeo786/Rufaydium-Webdriver#6]
Although I suppose there aren't that many [Opera browser](https://www.opera.com/) + AutoHotkey users - they do have their own webdriver which they seem to update on a regular basis https://github.com/operasoftware/operachromiumdriver/releases/

Perhaps worth adding at some point.

**Comment by Xeo786** [comment]
Rufaydium based on w3c standereds therefore you just download opera driver manually and pass it to Rufaydium I would work but few chrome methods does not work.

**Comment by Xeo786** [comment]
I saw you have old fork which is discontinued, you should delete that repo and refork Rufaydium

**Comment by Xeo786** [comment]
I am closing this issue, this ability soon bee added in future
