### ISSUE TITLE
'getElementsbyXpath' is not working.

### ISSUE THREAD

**Issue by cinqfoil** [Xeo786/Rufaydium-Webdriver#8]
I'm glad to know your Rufaydium-Webdriver recently.
I am trying to use 'getElementsbyXpath'. But, it's not working.

Could you explain why it's not working?

-----------------------------------------
#Include Rufaydium.ahk
global page

Chrome := new Rufaydium("chromedriver.exe")
page := Chrome.NewSession()
page.Navigate("https://www.google.com")
return

^1::
xpath := "/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input"
el := page.getElementsbyXpath(xpath)
el.value := "test"
return

**Comment by Xeo786** [comment]
You are using 'getElements' it should return array, therefore you should use 
```
el := page.getElementsbyXpath(xpath)
el[0].value := "test"
```
OR
```
for i, e in el
    msgbox, % e.value
```

**Comment by Xeo786** [comment]
msg return empty because its has no value attribute but code working that xpath receing sendkays
```autohotkey
#Include Rufaydium.ahk
Chrome := new Rufaydium("chromedriver.exe")

Page := Chrome.getSessionByUrl("https://www.google.com")
if !isobject(page)
{
	page := Chrome.NewSession()
	page.Navigate("https://www.google.com")
}

xpath := "html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input"
el := page.getElementsbyXpath(xpath)
for i, e in el
    e.sendkey("test")
return
```

**Comment by cinqfoil** [comment]
Thank you. Your code is working well.
