### ISSUE TITLE
Capabilities.ahk unable to determine browser.

### ISSUE THREAD

**Issue by hotcheesesoup** [Xeo786/Rufaydium-Webdriver#9]
Just updated to the newest version. It appears ` __new(browser,Options,platform:="windows",notify:=false)` isn't returning anything for `browser`. Hardcoding "chrome" on lines 14 and 20 on Capabilities.ahk made it start up. 

I think the issue might be on line 26 on Rufaydium.ahk. `this.Driver` doesn't seem to return anything currently.

```
---------------------------
Rufaydium WebDriver Support Error
---------------------------
invalid argument

invalid argument: cannot parse capability: browserName
from invalid argument: cannot be empty
---------------------------
```

Trying to add the default `browser:="chrome"` and  `Options:=""` on Capabilities.ahk also gives the above error.

Could be user error. Thanks!

**Comment by Xeo786** [comment]
what driver you have passed can you show me the code

**Comment by hotcheesesoup** [comment]
Sure. All I'm doing is this:

```
Chrome := new Rufaydium("chromedriver.exe")
Chrome.capabilities.setUserProfile()
```

I added `browser := "chrome"` on line 9 of Capabilities.ahk to get around the error.

Do you want to see anything else?

**Comment by Xeo786** [comment]
you should pass parameters to `Chrome.capabilities.setUserProfile()` its passing arguments for user profile directory for chrome
check first example there https://github.com/Xeo786/Rufaydium-Webdriver#capabilities-class

**Comment by hotcheesesoup** [comment]
I don't think the arguments for the setUserProfile are the issue. It just defaults to my main profile whether I add "Default" or not, but I'll add Default for consistency.

Sorry, I guess I bumped that line down to line 10, so my NOW line 9 is `browser := "chrome"`.

```
    __new(browser,Options,platform:="windows",notify:=false)
    {
	browser := "chrome" ; my new line 9 to get around browser being blank.
        this.options := Options
        this.cap := {}
        this.cap.capabilities := {}
        this.cap.capabilities.alwaysMatch := { this.options :{"w3c":json.true}}
        this.cap.capabilities.alwaysMatch.browserName := browser
        this.cap.capabilities.alwaysMatch.platformName := platform
        if(notify = false)
            this.AddexcludeSwitches("enable-automation")
        this.cap.capabilities.firstMatch := [{}]
        this.cap.desiredCapabilities := {}
        this.cap.desiredCapabilities.browserName := browser
    }
```

**Comment by Xeo786** [comment]
That line line 9 `is browser := "chrome".` won't do anything to Rufaydium or Sessions

**Comment by hotcheesesoup** [comment]
It was more to treat the symptoms of the error, not necessarily to fix the cause. I couldn't even get Chrome to open because of the error since the browser variable is blank.

`this.Driver` on line 26 of Rufaydium.ahk returns "chromedriver". I don't see where `this.Driver.browser` is defined though.  Adding `this.Driver.browser := "chrome"` prevented the error.

`this.capabilities := new capabilities(this.Driver.browser,this.Driver.Options)
`

Should there be an if statement around here?

```
if (this.Driver == "chromedriver")
    this.Driver.browser := "chrome"
else if (this.Driver == "msedgedriver")
    this.Driver.browser := "msedge" ; or whatever it is supposed to be called
```

**Comment by hotcheesesoup** [comment]
Ahh I think I see where it is in WDM.ahk. My older version has `this.browser` in it, but my newer one doesn't.

Was this just updated?

```
switch this.Name
{
	case "chromedriver" :
		this.Options := "goog:chromeOptions"
		this.browser := "chrome"

	case "msedgedriver" : 
		this.Options := "ms:edgeOptions"
		this.browser := "msedge"
	case "geckodriver" : 
		this.Options := "moz:firefoxOptions"
		this.browser := "firefox"
}
```

**Comment by hotcheesesoup** [comment]
Not sure why my version was missing `this.browser`. Sorry for wasting your time!
